### ISSUE TITLE
Enum case sensitivity in swagger.json causes problem

### ISSUE THREAD

**Issue by brammittendorff-dd** [MyPureCloud/purecloud_api_sdk_javascript#16]
We used your swagger.json to generate a php sdk. The problem we have now is that the enum values from the response of the rest api returns lowercase.

The enum values in the swagger.json file are uppercase. So the values are invalid when they are compared by the generated code.

**Comment by T-Boss** [comment]
Enum parsing should always be done case-insensitively and the SDK should handle unknown values (in case it's out of date). This is what the existing SDKs do. There's currently an API bug that's causing the documented vs. actual values to be different. It will be resolved soon, but being case-tolerant is a best practice anyway.

Would you mind posting on the Developer Forum to continue this discussion? If you've used the swagger-codegen project to generate the SDK and would like to share, we can discuss accepting a PR to add it to our SDK generation process.

**Comment by T-Boss** [comment]
Whoops, forgot the Developer Forum link: https://developer.mypurecloud.com/forum/c/platform-api

**Comment by Potherca** [comment]
Question: What is the reason that the values of the enums are uppercase in the `swagger.json` to begin with?
On a side-note, how is the `swagger.json` generated? (it might very well be possible to fix things there).

**Comment by Potherca** [comment]
> Would you mind posting on the Developer Forum to continue this discussion?

I'm not sure what the response time on the forums is but it has now been a week without response... :disappointed:

**Comment by T-Boss** [comment]
I've been out of the office for Thanksgiving. Will look at it today.
