### ISSUE TITLE
Broken links within the Readme 

### ISSUE THREAD

**Issue by pansj** [MyPureCloud/purecloud_api_sdk_javascript#3]
There are broke links within the Readme.
These are some of the ones I was trying to view. 
[http://localhost:4567/api/rest/client-libraries/javascript/latest/](http://localhost:4567/api/rest/client-libraries/javascript/latest/)
[http://mypurecloud.github.io/purecloud_javascript_client/examples/index.html](http://mypurecloud.github.io/purecloud_javascript_client/examples/index.html)
[https://github.com/MyPureCloud/purecloud_javascript_client/examples](https://github.com/MyPureCloud/purecloud_javascript_client/examples)

**Comment by KevinGlinski** [comment]
Thanks, fixed.
