### ISSUE TITLE
handling timeouts

### ISSUE THREAD

**Issue by gildas** [MyPureCloud/purecloud_api_sdk_javascript#6]
When you have an access_token and call PureCloudSession.authorize (to verify the token), if there is any error that happens while GET /users/me, you cannot be aware of it.

It happens the Tokyo office is really slow today (we need to reboot the router) and the authorize method will simply timeout (the REST request timeout is set to 2 seconds), this cause the web page to loop infinitely if the redirect_url is set to the same page.

See the console log: https://gist.github.com/gildas/6b3d46199772023bfd9e
Note: in that log, I hacked the PureCloudSession.authorize method to show the error /users/me gets:

```javascript
21386             }).error(function(jqxhr, error_status, error_thrown){
21387               console.error("Failure while GET /users/me: %s (%s)", error_status, error_thrown);
21388                 //don't have an auth token yet
21389                 authRedirect();
21390             });
```

**Comment by gildas** [comment]
IMO, we should allow to fall back to the calling code on errors (or some errors), so the developer can do something about it.
I tried to use some .fail, but the defer used by authorize does not allow it.

**Comment by gildas** [comment]
In the same vein, maybe allowing us to change the timeout of that generic REST call would be nice.
And maybe, a retry count?!?

**Comment by KevinGlinski** [comment]
Timeout added in https://github.com/MyPureCloud/purecloud_api_sdk_javascript/commit/77eb22f258c5f9bd4b7eb2b717f678a69ffb690e
