### ISSUE TITLE
Support OAuth "Rehydration" on logout

### ISSUE THREAD

**Issue by justinaray** [MyPureCloud/purecloud_api_sdk_javascript#8]
If you pass the same query string variables to `logout` that you do to `authenticate` (i.e. `redirect_uri`, `client_id`, and `response_type`), the server will will reattempt login and prime the oauth flow for the next user attempt.

This has the effect of letting the user sign right back into the app they left.

Happy to help with the PR if you want :)

**Comment by KevinGlinski** [comment]
So i just tried this, I logged in, then logged out so it redirected back to login.mypurecloud.com, but since it remembered my login cookie, redirected back to my app.  making it impossible to logout.  Is that expected?

**Comment by justinaray** [comment]
Hmm ... just tested it and it worked.  Will follow up with the oauth guys.
